on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: akhtar.azurecr.io
        username: ${{ secrets.acr_akhtar_username }}
        password: ${{ secrets.acr_akhtar_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t akhtar.azurecr.io/test:${{ github.sha }}
        docker push akhtar.azurecr.io/test:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_test_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep testa594 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace testa594`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: testa594
        container-registry-url: akhtar.azurecr.io
        container-registry-username: ${{ secrets.acr_akhtar_username }}
        container-registry-password: ${{ secrets.acr_akhtar_password }}
        secret-name: testdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: testa594
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          akhtar.azurecr.io/test:${{ github.sha }}
        imagepullsecrets: |
          testdockerauth
